### PR TITLE
Fixing login request loop when PKCE is mandatory on Asgardeo console but disabled on the SDK

### LINKED ISSUE #14: Login request loop when PKCE is mandatory on Asgardeo console but disabled on the SDK
**Description:**

If a user tries to login when **PKCE is set to mandatory on the Asgardeo console** and **disabled on the express SDK**, the application get stuck on a login request loop. 

**Affected Product Version:**

- SDK Version: 0.1.0

**OS, DB, other environment details and versions:**

- OS: MacOs Monterey
- Chrome: Version 103.0.5060.114    

**Steps to reproduce:**

1. Configure an application on Asgardeo console with PKCE set to `Mandatory`.
2. Set `enablePKCE` flag to `true` on AsgardeoExpressClient configs in the local application.
3. Try to sign in.

### PR DESCRIPTION
**Pull request by nipunsampath**

### CODE REVIEW

File: lib/src/utils/express-utils.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+     * @param url - URL to be checked.
+     *
+     * @returns {boolean} - True if the URL contains an error.
+     */
+    public static hasErrorInURL(url: string): boolean {
+        const AUTH_CODE_REGEXP: RegExp = /[?&]error=[^&]+/;
+
+        return AUTH_CODE_REGEXP.test(url);
+    }
+}
```
Comment (thivi) [inline lib/src/utils/express-utils.ts]: Leave an empty line.

**Review by thivi — APPROVED** [review]

**Review by thivi — APPROVED** [review]

File: lib/src/utils/express-utils.ts (hunk 1 above)
Comment (thivi) [inline lib/src/utils/express-utils.ts]:
```suggestion
}

```

**Review by thivi — APPROVED** [review]

File: lib/src/utils/express-utils.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+    /**
+     * Util function to check if the URL contains an error.
+     *
+     * @param url - URL to be checked.
+     *
+     * @returns {boolean} - True if the URL contains an error.
+     */
+    public static hasErrorInURL(url: string): boolean {
+        const AUTH_CODE_REGEXP: RegExp = /[?&]error=[^&]+/;
```
Comment (ThaminduDilshan) [inline lib/src/utils/express-utils.ts:11]: Shall we extract this constant to a class variable?
